// This file is auto-generated...
public enum eTextID { 
	Yes,
	No,
	Cancel,
	Config_Title,
	Config_Worth_GachaCoin_Copper,
	Config_Worth_GachaCoin_Silver,
	Config_Worth_GachaCoin_Gold,
	Config_Worth_GachaCoin_Plat,
	Config_Worth_AncientBook,
	Config_Worth_SkillBook,
	Config_SalesNum_SkillBook_Base,
	Config_SalesNum_SkillBook_Add,
	Config_SalesLvLotRate_SkillBook_High,
	Config_SalesLvLotRate_SkillBook_Middle,
	Config_SalesLvLotRate_SkillBook_Low,
	Config_SalesLv_SkillBook_High,
	Config_SalesLv_SkillBook_Middle,
	Config_SalesLv_SkillBook_Low,
	Msg_PayEnd,
	Msg_HaveCoin,
	Say_HaveCoin,
}
